upd ci !!release (ci test)

diff --git a/.github/workflows/gradle_ci_modified.yaml b/.github/workflows/gradle_ci_modified.yaml
--- a/.github/workflows/gradle_ci_modified.yaml
+++ b/.github/workflows/gradle_ci_modified.yaml
@@ -91,18 +91,19 @@ jobs:
           git fetch --all --tags
           #exit 1
           VERSION=$(./gradlew properties | grep version | awk '{print $2}')
-          echo "Version $VERSION"
+          [[ -z $(git tag -l $VERSION) ]]  # fail if not empty, i.e. if tag exists
+          #echo "Version $VERSION"
+          #echo "----"
+          #git tag -l $VERSION
+          #echo "----"
+          #git tag -l
           echo "----"
-          git tag -l $VERSION
-          echo "----"
-          git tag -l
-          echo "----"
-          [[ ! -z $(git tag -l $VERSION) ]] && exit 1
+          #[[ ! -z $(git tag -l $VERSION) ]] && exit 1
           #          echo "Version $VERSION"
           #          [[ -z $(git tag -l $VERSION) ]]
-          #          if [ ! -z $(git tag -l $VERSION) ]; then
-          #            echo "Tag $VERSION already exists"
-          #            exit 1
+          #           if [ ! -z $(git tag -l $VERSION) ]; then
+          #             echo "Tag $VERSION already exists"
+          #             exit 1
           #          fi
 
           echo "::set-output name=result::$VERSION"
